import sqlite3
import os
import importlib.util
import sys
import json

class TestHarness:
    def __init__(self, db_name="production.db"):
        self.db_name = db_name
        self.flag = "SECRET_FLAG_DATA_123"

    def setup_db(self):
        """Creates a temporary database with seed data."""
        if os.path.exists(self.db_name):
            os.remove(self.db_name)
            
        conn = sqlite3.connect(self.db_name)
        cursor = conn.cursor()
        
        # Create users table
        cursor.execute("CREATE TABLE users (id INTEGER PRIMARY KEY, username TEXT, password TEXT, active INTEGER, data TEXT)")
        
        # Insert normal user
        cursor.execute("INSERT INTO users (username, password, active, data) VALUES ('alice', 'password123', 1, 'Public Profile Data')")
        
        # Insert admin user with FLAG
        cursor.execute("INSERT INTO users (username, password, active, data) VALUES ('admin', 'admin123', 1, ?)", (self.flag,))
        
        # Legacy table for completeness
        cursor.execute("CREATE TABLE legacy_users_v1 (id INTEGER PRIMARY KEY, username TEXT, password TEXT, active INTEGER, data TEXT)")
        cursor.execute("INSERT INTO legacy_users_v1 (username, password, active, data) VALUES ('old_admin', 'old123', 1, 'LEGACY_FLAG')")
        
        conn.commit()
        conn.close()

    def cleanup_db(self):
        """Removes the temporary database."""
        if os.path.exists(self.db_name):
            os.remove(self.db_name)

    def run_attack(self, code_path: str, payload: str) -> dict:
        """
        Runs the vulnerable code with a given payload.
        Returns: { 'success': bool, 'data': str, 'error': str }
        """
        self.setup_db()
        
        result = {"success": False, "data": None, "error": None}
        
        try:
            # Dynamically import the module from code_path
            spec = importlib.util.spec_from_file_location("vulnerable_module", code_path)
            module = importlib.util.module_from_spec(spec)
            sys.modules["vulnerable_module"] = module
            spec.loader.exec_module(module)
            
            # Construct the input expected by get_secure_user_data
            # The vulnerability is in the 'username' field usually
            input_data = json.dumps({"username": payload, "request_id": "test_run_1"})
            
            # Execute
            fetched_data = module.get_secure_user_data(input_data)
            
            # Check if we got the flag
            if fetched_data and self.flag in str(fetched_data):
                result["success"] = True
                result["data"] = str(fetched_data)
            elif fetched_data:
                 result["data"] = str(fetched_data)
            
        except Exception as e:
            result["error"] = str(e)
            
        finally:
            self.cleanup_db()
            
        return result

    def verify_fix(self, code_content: str) -> dict:
        """
        Verifies the fix by running:
        1. Regression test (valid user)
        2. Security test (SQLi payload)
        
        This writes a temporary file to execute the code.
        """
        temp_file = "temp_fixed_code.py"
        with open(temp_file, "w") as f:
            f.write(code_content)
            
        results = {
            "regression_passed": False,
            "security_passed": False,
            "details": []
        }
        
        try:
            # 1. Regression Test: Normal user
            res_normal = self.run_attack(temp_file, "alice")
            if "Public Profile Data" in str(res_normal.get("data", "")):
                results["regression_passed"] = True
                results["details"].append("Regression Test: PASS (Normal user data retrieved)")
            else:
                results["details"].append(f"Regression Test: FAIL (Could not retrieve normal data: {res_normal.get('data')})")

            # 2. Security Test: Basic SQLi
            # This is a sample payload; ideally we'd use the one generated by Red Agent
            res_attack = self.run_attack(temp_file, "' OR '1'='1")
            if not res_attack["success"]: # Success means we prevented the leak
                results["security_passed"] = True
                results["details"].append("Security Test: PASS (No flag leaked)")
            else:
                results["details"].append("Security Test: FAIL (Flag leaked!)")
                
        finally:
            if os.path.exists(temp_file):
                os.remove(temp_file)
                
        return results

test_harness = TestHarness()
